In [8]:
import numpy as hs

In [15]:
import matplotlib.pyplot as plt

In [16]:
hs.array([1,3,5,7,9])

array([1, 3, 5, 7, 9])

In [20]:
hs.zeros(5)

array([0., 0., 0., 0., 0.])

In [21]:
hs.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [22]:
hs.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [24]:
hs.linspace(5,10,6)

array([ 5.,  6.,  7.,  8.,  9., 10.])

In [25]:
hs.linspace(1,20,50)

array([ 1.        ,  1.3877551 ,  1.7755102 ,  2.16326531,  2.55102041,
        2.93877551,  3.32653061,  3.71428571,  4.10204082,  4.48979592,
        4.87755102,  5.26530612,  5.65306122,  6.04081633,  6.42857143,
        6.81632653,  7.20408163,  7.59183673,  7.97959184,  8.36734694,
        8.75510204,  9.14285714,  9.53061224,  9.91836735, 10.30612245,
       10.69387755, 11.08163265, 11.46938776, 11.85714286, 12.24489796,
       12.63265306, 13.02040816, 13.40816327, 13.79591837, 14.18367347,
       14.57142857, 14.95918367, 15.34693878, 15.73469388, 16.12244898,
       16.51020408, 16.89795918, 17.28571429, 17.67346939, 18.06122449,
       18.44897959, 18.83673469, 19.2244898 , 19.6122449 , 20.        ])

In [27]:
x = hs.linspace(5,10,6)
y = x**2

In [28]:
x

array([ 5.,  6.,  7.,  8.,  9., 10.])

In [29]:
x = hs.linspace(5,30,8)
y = x**2

In [30]:
x

array([ 5.        ,  8.57142857, 12.14285714, 15.71428571, 19.28571429,
       22.85714286, 26.42857143, 30.        ])

In [32]:
a1 = hs.arange(0,10,0.5)

In [33]:
a1

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [34]:
a2 = hs.arange(2,8,4)

In [35]:
a2

array([2, 6])

In [37]:
a1[:6]

array([0. , 0.5, 1. , 1.5, 2. , 2.5])

In [38]:
a1[7]

3.5

In [39]:
a1[6:]

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. ,
       9.5])